[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.5.53", features = [ "derive" ] }
geoutils = { workspace = true }
juriji = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shared = { path = "../shared" }
sqlx = { workspace = true }
squalid = { workspace = true }
tokio = { workspace = true, features = [ "fs" ] }
uuid = { workspace = true }
